[package]
name = "aoc21"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
lazy_static = "1.5.0"
memoize = "0.4.2"
nalgebra = "0.33.2"
nom = "7.1.3"
rayon = "1.10.0"
regex = "1.11.1"
