#!/usr/bin/env bash
set -euo pipefail

day=$1
if [[ -z $day ]]; then
    echo >&2 "Usage: $0 <day>"
    exit 1
fi

inputFile="inputs/day${day}"
if [[ ! -e $inputFile ]]; then
    echo "Downloading input file"
    sessionToken=$(cat ~/.config/aoc/session_token)
    wget --no-cookies --header "Cookie: session=${sessionToken}" -O "$inputFile" https://adventofcode.com/2021/day/${day}/input
fi


binFile="src/bin/day${day}.rs"
if [[ ! -e $binFile ]]; then
    testInput=$(
        xmlstarlet fo -H <(curl https://adventofcode.com/2021/day/$day) 2>/dev/null \
        | xmlstarlet sel -t -v '//pre[1]/code[1]')

    testInput=${testInput//&gt;/>}
    testInput=${testInput//&lt;/<}

    cat >"$binFile" <<EOF
aoc21::simple_main!(${day});

type Input = Vec<String>;
type Output = usize;

fn part1(inp: &Input) -> Output {
    0
}

fn part2(_inp: &Input) -> Output {
    0
}

#[allow(dead_code)]
const TEST_INPUT: &str = "${testInput}";

aoc21::test_part1!(TEST_INPUT, 0);
aoc21::test_part2!(TEST_INPUT, 0);
EOF
fi
